name: "CI checks"
description: "Makes sure all packages are buildable"
runs:
  using: "composite"
  steps:
    - name: Test
      run: npm run test
      shell: bash

    - name: Build
      run: npm run build
      shell: bash
